basic:
    name: 'CUPE WP5'
    environments:
        production: 'https://test-wp5.pantheonsite.io/'
        staging: 'https://dev-wp5.pantheonsite.io/'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - '--sample1-wp5-cupe'
        - '--cupe3912'
        - '--unpaidworkwontfly'
        - '--atcomponent'
        - '--scfp2881'
        - '--cupe4600'
        - '--cupe5678'
        - '--cupe728'
        - '--3651-cupe'
        - '--cupe5167'
        - '--5441-cupe'
        - '--cupe561'
        - '--4475-scfp'
        - '--1252-cupe'
        - '--606-cupe'
        - '--cupe3338'
        - '--cupe1883'
        - '--cupeltc'
        - '--cupepei'
        - '--blendedfinancecritique'
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
